//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public Admins()
        {
            this.Doctors = new HashSet<Doctors>();
        }
    
        public int Id { get; set; }
        public string ClinicName { get; set; }
        public string AspNetUserId { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<Doctors> Doctors { get; set; }
    }
}
