//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempts
    {
        public int Id { get; set; }
        public int MotionId { get; set; }
        public int SessionId { get; set; }
        public double MaxAngle { get; set; }
        public double MaxProgress { get; set; }
        public System.TimeSpan CompletedTime { get; set; }
        public double Velocity { get; set; }
        public string FinishedBy { get; set; }
        public double PlaneAngle { get; set; }
        public double SpinalAngle { get; set; }
        public double ShoulderAngle { get; set; }
    
        public virtual Motions Motions { get; set; }
        public virtual Sessions Sessions { get; set; }
    }
}
