//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMotions
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int MotionId { get; set; }
        public int RequiredCount { get; set; }
        public int MotionOrder { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Motions Motions { get; set; }
    }
}
