//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class localHabEntities : DbContext
    {
        public localHabEntities()
            : base("name=localHabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Attempts> Attempts { get; set; }
        public virtual DbSet<CourseMotions> CourseMotions { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Motions> Motions { get; set; }
        public virtual DbSet<MotionTemplates> MotionTemplates { get; set; }
        public virtual DbSet<PatientCourses> PatientCourses { get; set; }
        public virtual DbSet<PatientDiagnostics> PatientDiagnostics { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<PatientSchedule> PatientSchedule { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
    }
}
