//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotionTemplates
    {
        public MotionTemplates()
        {
            this.Motions = new HashSet<Motions>();
            this.PatientDiagnostics = new HashSet<PatientDiagnostics>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string RotationPlane { get; set; }
        public string AxisJoint { get; set; }
        public string RimJoint { get; set; }
        public string RimJoint2 { get; set; }
        public int DefaultStartAngle { get; set; }
        public int MinStartAngle { get; set; }
        public int DefaultEndAngle { get; set; }
        public int MaxEndAngle { get; set; }
        public int StartDeviation { get; set; }
        public Nullable<int> EndDeviation { get; set; }
        public int DefaultPlaneDeviation { get; set; }
        public int DefaultSpinalDeviation { get; set; }
        public int DefaultShoulderDeviation { get; set; }
        public bool DefaultCheckSpinalBalance { get; set; }
        public bool DefaultCheckShoulderBalance { get; set; }
        public int ViewStartAngle { get; set; }
        public int DefaultRequiredCount { get; set; }
        public int Direction { get; set; }
        public string InstructionIcon { get; set; }
    
        public virtual ICollection<Motions> Motions { get; set; }
        public virtual ICollection<PatientDiagnostics> PatientDiagnostics { get; set; }
    }
}
