//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motions
    {
        public Motions()
        {
            this.Attempts = new HashSet<Attempts>();
            this.CourseMotions = new HashSet<CourseMotions>();
        }
    
        public int Id { get; set; }
        public int StartAngle { get; set; }
        public int EndAngle { get; set; }
        public bool CheckSpinalBalance { get; set; }
        public bool CheckShoulderBalance { get; set; }
        public int ShoulderDeviation { get; set; }
        public int PlaneDeviation { get; set; }
        public int SpinalDeviation { get; set; }
        public int MotionTemplateId { get; set; }
    
        public virtual ICollection<Attempts> Attempts { get; set; }
        public virtual ICollection<CourseMotions> CourseMotions { get; set; }
        public virtual MotionTemplates MotionTemplates { get; set; }
    }
}
