//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiagnostics
    {
        public int Id { get; set; }
        public System.DateTime DiagnosticsDate { get; set; }
        public int PatientId { get; set; }
        public int MotionTemplateId { get; set; }
        public double ResultAngle { get; set; }
    
        public virtual MotionTemplates MotionTemplates { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
