//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSchedule
    {
        public PatientSchedule()
        {
            this.Sessions = new HashSet<Sessions>();
        }
    
        public int Id { get; set; }
        public System.DateTime PlanDate { get; set; }
        public int PatientId { get; set; }
        public int CourseId { get; set; }
        public int CourseOrder { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual ICollection<Sessions> Sessions { get; set; }
    }
}
