//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientCourses
    {
        public int PatientId { get; set; }
        public int CourceId { get; set; }
        public int PatientCourseOrder { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
