//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public Patients()
        {
            this.PatientCourses = new HashSet<PatientCourses>();
            this.PatientDiagnostics = new HashSet<PatientDiagnostics>();
            this.PatientSchedule = new HashSet<PatientSchedule>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int DoctorId { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual ICollection<PatientCourses> PatientCourses { get; set; }
        public virtual ICollection<PatientDiagnostics> PatientDiagnostics { get; set; }
        public virtual ICollection<PatientSchedule> PatientSchedule { get; set; }
    }
}
