//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habilect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public Sessions()
        {
            this.Attempts = new HashSet<Attempts>();
        }
    
        public int Id { get; set; }
        public int GameId { get; set; }
        public int PatientScheduleId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual ICollection<Attempts> Attempts { get; set; }
        public virtual PatientSchedule PatientSchedule { get; set; }
    }
}
